// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoForest_Data.Context;

namespace TechnoForest_Data.Migrations
{
    [DbContext(typeof(TechnoForestContext))]
    [Migration("20200110130817_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.MobilePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBought")
                        .HasColumnType("bit");

                    b.Property<string>("Memory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SizeOfDisplay")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MobilePhones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            IsBought = false,
                            Memory = "32 GB",
                            Model = "7 Plus",
                            Picture = "~/images/Black7Plus.jpg",
                            Price = 929.36m,
                            ProductName = "Iphone",
                            SizeOfDisplay = 5.5
                        },
                        new
                        {
                            Id = 2,
                            Color = "Pink",
                            IsBought = false,
                            Memory = "32 GB",
                            Model = "7 Plus",
                            Picture = "~/images/Pink7Plus.jpg",
                            Price = 1029.36m,
                            ProductName = "Iphone",
                            SizeOfDisplay = 5.5
                        },
                        new
                        {
                            Id = 3,
                            Color = "Gray",
                            IsBought = false,
                            Memory = "64 GB",
                            Model = " 6S",
                            Picture = "~/images/Gray6s.jpg",
                            Price = 1029.36m,
                            ProductName = "Iphone",
                            SizeOfDisplay = 5.5
                        },
                        new
                        {
                            Id = 4,
                            Color = "Gray",
                            IsBought = false,
                            Memory = "64 GB",
                            Model = "X",
                            Picture = "~/images/Xgray.jpg",
                            Price = 1849.99m,
                            ProductName = "Iphone",
                            SizeOfDisplay = 5.7999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Color = "Pink",
                            IsBought = false,
                            Memory = "64 GB",
                            Model = "X",
                            Picture = "~/images/Xgray.jpg",
                            Price = 2049.99m,
                            ProductName = "Iphone",
                            SizeOfDisplay = 5.7999999999999998
                        });
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AddTOCart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MobilePhoneId")
                        .HasColumnType("int");

                    b.Property<int?>("TVsId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MobilePhoneId")
                        .IsUnique()
                        .HasFilter("[MobilePhoneId] IS NOT NULL");

                    b.HasIndex("TVsId")
                        .IsUnique()
                        .HasFilter("[TVsId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("WashingMachineId")
                        .IsUnique()
                        .HasFilter("[WashingMachineId] IS NOT NULL");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.TV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsBought")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBought = false,
                            Model = "KD55XG8196BAEP",
                            Price = 1389m,
                            ProductName = "Sony",
                            Size = 55.0
                        },
                        new
                        {
                            Id = 2,
                            IsBought = false,
                            Model = "BRAVIA",
                            Price = 2899m,
                            ProductName = "Sony",
                            Size = 55.0
                        },
                        new
                        {
                            Id = 3,
                            IsBought = false,
                            Model = "43LK5100PLA",
                            Price = 428m,
                            ProductName = "LG",
                            Size = 43.0
                        },
                        new
                        {
                            Id = 4,
                            IsBought = false,
                            Model = "70UI9362E",
                            Price = 1449.99m,
                            ProductName = "Sharp",
                            Size = 70.0
                        },
                        new
                        {
                            Id = 5,
                            IsBought = false,
                            Model = "32PFS4132/12",
                            Price = 388m,
                            ProductName = "PHILIPS",
                            Size = 32.0
                        });
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BuyProduct")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.WashingMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsBought")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WashingCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WashingMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBought = false,
                            Model = "WW70K44305W",
                            Price = 609m,
                            ProductName = "Samsung",
                            WashingCapacity = 7
                        },
                        new
                        {
                            Id = 2,
                            IsBought = false,
                            Model = "WMY81483LMB1",
                            Price = 669.99m,
                            ProductName = "Beko",
                            WashingCapacity = 8
                        },
                        new
                        {
                            Id = 3,
                            IsBought = false,
                            Model = "L9WBA61B",
                            Price = 2899.99m,
                            ProductName = "AEG",
                            WashingCapacity = 9
                        },
                        new
                        {
                            Id = 4,
                            IsBought = false,
                            Model = "TDLR 70210",
                            Price = 599m,
                            ProductName = "Whirlpool",
                            WashingCapacity = 8
                        },
                        new
                        {
                            Id = 5,
                            IsBought = false,
                            Model = "F2J6HM0W",
                            Price = 799m,
                            ProductName = "LG",
                            WashingCapacity = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.MobilePhone", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany("MobilePhones")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.ShoppingCart", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.MobilePhone", "MobilePhones")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("TechnoForest_Data.Entity.ShoppingCart", "MobilePhoneId");

                    b.HasOne("TechnoForest_Data.Entity.TV", "TVs")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("TechnoForest_Data.Entity.ShoppingCart", "TVsId");

                    b.HasOne("TechnoForest_Data.Entity.User", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId");

                    b.HasOne("TechnoForest_Data.Entity.WashingMachine", "WashingMachines")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("TechnoForest_Data.Entity.ShoppingCart", "WashingMachineId");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.TV", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany("TVs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TechnoForest_Data.Entity.WashingMachine", b =>
                {
                    b.HasOne("TechnoForest_Data.Entity.User", null)
                        .WithMany("WashingMachines")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
